extraction:
  csharp:
    index:
      solution:
        - ./app/Spinner.sln
      nuget_restore: false
      all_solutions: true
      dotnet:
        arguments: "-f 6.0.302"
        version: "6.0.302"
      buildless: true