extraction:
  csharp:
    index:
      solution:
        - "./app/Spinner.sln"
      nuget_restore: true
      all_solutions: true
      dotnet:
        arguments: "-f net6.0"
        version: "6.0.302"