extraction:
  csharp:
    index:
      solution: "./app/Spinner.sln"
      nuget_restore: true
      dotnet:
        version: 6.0.301
      build_command:
      - "export PB_MODE=release"
      - "dotnet build ./app/Spinner.sln"