extraction:
  csharp:
    index:
      solution: "./app/Spinner.sln"
      nuget_restore: true
      dotnet: Auto
      build_command:
      - "export PB_MODE=release"
      - "dotnet build ./app/Spinner.sln"